autoload -Uz compinit
compinit

if [ "$(command -v starship)" ]; then
	eval "$(starship init zsh)"
fi

[ -L ~/.localrc ] && source ~/.localrc

for file ($DF/zsh/*.zsh); do
  source $file
done

autoload -U compinit && compinit
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/.docker/init-zsh.sh ] && source ~/.docker/init-zsh.sh
