# deprecated tap "homebrew/bundle"
# deprecated tap "homebrew/cask"
# error tap "homebrew/cask-versions"
# not needed tap "homebrew/core"
tap "warrensbox/tap"
tap "microsoft/mssql-release"
brew "ack"
brew "python@3.9"
brew "awscli", args: ["HEAD"]
brew "azcopy"
brew "azure-cli"
brew "htop"
brew "pipx"
brew "libssh2"
brew "curl"
# brew "diff-so-fancy"
# brew "eksctl"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
# brew "helm"
brew "jq"
# brew "kind"
# brew "kubernetes-cli"
brew "make"
brew "mas"
brew "node"
# brew "protobuf", args: ["HEAD"]
brew "rsync"
brew "starship"
brew "tldr"
brew "watch"
brew "zoxide"
brew "microsoft/mssql-release/mssql-tools"
# brew "warrensbox/tap/tfswitch"
# brew "terragrunt"
cask "1password", args: { appdir: "/Applications" }
cask "another-redis-desktop-manager"
cask "cyberduck", args: { appdir: "/Applications" }
cask "discord"
cask "docker", args: { appdir: "/Applications" }
cask "dotnet-sdk"
# cask "firefox-developer-edition", args: { appdir: "/Applications" }
# cask "google-drive"
# cask "gpg-suite", args: { appdir: "/Applications" }
cask "hammerspoon", args: { appdir: "/Applications" }
cask "postman"
cask "iterm2", args: { appdir: "/Applications" }
# cask "java", args: { appdir: "/Applications" }
# cask "jetbrains-toolbox", args: { appdir: "/Applications" }
# cask "keybase"
cask "royal-tsx", args: { appdir: "/Applications" }
# cask "slack", args: { appdir: "/Applications" }
cask "spotify"
cask "sublime-text", args: { appdir: "/Applications" }
# cask "tenor"
# cask "tunnelblick", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
# cask "vmware-fusion", args: { appdir: "/Applications" }
cask "microsoft-azure-storage-explorer"
cask "google-chrome"
cask "zoom"
cask "trilium-notes"

mas "Tailscale", id: 1475387142
